### ISSUE TITLE
SpawnerShop

### ISSUE THREAD

**Issue by 10BamberJ** [ctooley17/SpawnerShop#1]
https://www.spigotmc.org/resources/spawnershop-%E2%9E%9C-sign-gui-shops-%E2%9E%9C-permissions-%E2%9E%9C-economy.3005/

When I reload my server the config dosent reload, i also do /spawners reload it also dosent work.

Here is my Plugin list and Console. ill only put the things that contain "SpawnerShop"
Console: https://pastebin.com/x5EqWstc
Plugins: http://prntscr.com/hvcp1m

**Comment by ctooley21** [comment]
Same as Issue #6
