### ISSUE TITLE
Reserve Support

### ISSUE THREAD

**Issue by creatorfromhell** [ctooley17/SpawnerShop#3]
Hello, I am the developer of the plugin Reserve, a modern economy API with modern economy features in mind. As I am now ready to publicly push the API, I'm currently looking for developers to add support for it.

Link: https://github.com/TheNewEconomy/Reserve

Advantages over Vault:
- Multi-currency support
- Async support using Java's completeable futures
- Optional Extended API to allow third party plugins to add new currencies

Current Plugins that support Reserve:
- Towny
- ChestShop3
- MineBay

Current Providers/Planned Providers:
- The New Economy
- Towny Eco
- GemsEconomy

Thanks in advance,
creatorfromhell

**Comment by ctooley21** [comment]
@creatorfromhell Will be doing this mainly for the learning experience of supporting both vault and reserve at the same time. Something I haven't done before, should be interesting.

**Comment by ctooley21** [comment]
done in pr #17
